version: '2'
services:
  php:
    build: 
      context: ../php/
    volumes:
      - ./:/app
    depends_on: 
      - mysql  
    working_dir: /app
    restart: always
    networks:
      - code-network
    container_name: php
    links:
    - "mysql"

  web:
    build: 
      context: ../nginx/
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
    networks:
      - code-network  
    restart: always
    container_name: web

  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "9906:3306"
    volumes:
      - ./:/app
      - dbdata:/var/lib/mysql
    container_name: mysql

    networks:
      - code-network 
         
 
volumes:
  dbdata:

networks:
  code-network:
    driver: bridge    